---
- name: Assert supported templates
  assert:
    that:
      - item.key in  _pki_templates
    quiet: true
  with_dict: "{{ ca_templates }}"
  when: inventory_hostname in groups[pki_intermediate_group]
