---
- name: Assert proper distribution
  assert:
    that:
      - ansible_distribution in ['Ubuntu', 'Archlinux']
    quiet: true

- name: Assert supported templates
  assert:
    that:
      - item.key in  _pki_templates
    quiet: true
  loop: "{{ ca_templates | dict2items }}"
  when: inventory_hostname in groups[pki_intermediate_group]
