---
- name: Create openssl-base.cnf
  template:
    src: templates/openssl-base.cnf.j2
    dest: "{{ _ca_dirs['_ca_cnf'].path }}/openssl-base.cnf"
    owner: root
    group: root
    mode: 0644

- name: Create req-intermediate.cnf
  template:
    src: templates/req-intermediate.cnf.j2
    dest: "{{ _ca_dirs['_ca_cnf'].path }}/req-intermediate.cnf"
    owner: root
    group: root
    mode: 0600

- name: Create crl.cnf
  template:
    src: templates/crl.cnf.j2
    dest: "{{ _ca_dirs['_ca_cnf'].path }}/crl.cnf"
    owner: root
    group: root
    mode: 0644

- name: Create req templates
  template:
    src: "templates/req/req-{{ item.key }}.cnf.j2"
    dest: "{{ _ca_dirs['_ca_cnf_req'].path }}/req-{{ item.key }}.cnf"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ ca_templates }}"

- name: Create ca templates
  template:
    src: "templates/ca/ca-{{ item.key }}.cnf.j2"
    dest: "{{ _ca_dirs['_ca_cnf_ca'].path }}/ca-{{ item.key }}.cnf"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ ca_templates }}"
